
[context.production]
command = "yarn generate-deploy && next build"
publish = ".next"
[context.production.environment]
NEXT_PUBLIC_SUPABASE_URL = 'https://fororflyhxeircqexslh.supabase.co'
NEXT_PUBLIC_SUPABASE_PROJECT_ID = "fororflyhxeircqexslh"
NEXT_PUBLIC_SITE_URL = 'https://drillang.netlify.app/'
NEXT_PUBLIC_CONTEXT = "prod"


[context.branch-deploy]
command = "yarn generate-deploy && next build"
publish = ".next"
[context.branch-deploy.environment]
NEXT_PUBLIC_SUPABASE_URL = 'https://fororflyhxeircqexslh.supabase.co'
NEXT_PUBLIC_SUPABASE_PROJECT_ID = "fororflyhxeircqexslh"
NEXT_PUBLIC_SITE_URL = 'https://drillang.netlify.app/'
NEXT_PUBLIC_CONTEXT = "branch-deploy"


[context.development]
command = "yarn generate && next build"
publish = ".next"
[context.development.environment]
NEXT_PUBLIC_SUPABASE_URL = 'https://fororflyhxeircqexslh.supabase.co'
NEXT_PUBLIC_SUPABASE_PROJECT_ID = "fororflyhxeircqexslh"
NEXT_PUBLIC_SITE_URL = 'https://drillang.netlify.app/'
NEXT_PUBLIC_CONTEXT = "development"


[dev]
command = "next dev"
port = 8888
targetPort = 3000
context = "dev"

