env:
  es6: true
  node: true
  jest: true
  browser: true
  commonjs: false
extends:
  - './.eslintrc.yml'
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: module
plugins: []
