env:
  es6: true
  node: true
  browser: true
  commonjs: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - next
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    experimentalDecorators: true
    jsx: true
  sourceType: module
  project: "tsconfig.json"
plugins:
  - prettier
  - react
  - "@typescript-eslint/eslint-plugin"
  - simple-import-sort
  - react-hooks
rules:
  prettier/prettier:
    - error
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/react-in-jsx-scope: "off"
  react/prop-types: off
  react/display-name: off
  react/no-deprecated: warn
  eol-last: error
  no-multiple-empty-lines: error
  radix: error
  eqeqeq: ["error"]
  no-undef: 0        # https://github.com/eslint/typescript-eslint-parser/issues/416
  no-unused-vars: 0  # https://github.com/eslint/typescript-eslint-parser/issues/457
  simple-import-sort/imports: ["error", { "groups": [["^\\u0000", "^@?\\w", "^[^.]"]] }]
  react-hooks/rules-of-hooks: "error"
  react-hooks/exhaustive-deps: "error"
  no-console: "error"
globals:
  process: readonly
