create table "public"."tutor_topic" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "messages" jsonb,
    "instructions" text,
    "lang" iso_639_language_code not null,
    "level" text not null
);


alter table "public"."tutor_topic" enable row level security;

alter table "public"."phrase" add column "note" text;

CREATE UNIQUE INDEX tutor_topic_pkey ON public.tutor_topic USING btree (id);

alter table "public"."tutor_topic" add constraint "tutor_topic_pkey" PRIMARY KEY using index "tutor_topic_pkey";

alter table "public"."tutor_topic" add constraint "tutor_topic_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."tutor_topic" validate constraint "tutor_topic_user_id_fkey";

grant delete on table "public"."tutor_topic" to "anon";

grant insert on table "public"."tutor_topic" to "anon";

grant references on table "public"."tutor_topic" to "anon";

grant select on table "public"."tutor_topic" to "anon";

grant trigger on table "public"."tutor_topic" to "anon";

grant truncate on table "public"."tutor_topic" to "anon";

grant update on table "public"."tutor_topic" to "anon";

grant delete on table "public"."tutor_topic" to "authenticated";

grant insert on table "public"."tutor_topic" to "authenticated";

grant references on table "public"."tutor_topic" to "authenticated";

grant select on table "public"."tutor_topic" to "authenticated";

grant trigger on table "public"."tutor_topic" to "authenticated";

grant truncate on table "public"."tutor_topic" to "authenticated";

grant update on table "public"."tutor_topic" to "authenticated";

grant delete on table "public"."tutor_topic" to "service_role";

grant insert on table "public"."tutor_topic" to "service_role";

grant references on table "public"."tutor_topic" to "service_role";

grant select on table "public"."tutor_topic" to "service_role";

grant trigger on table "public"."tutor_topic" to "service_role";

grant truncate on table "public"."tutor_topic" to "service_role";

grant update on table "public"."tutor_topic" to "service_role";


