alter table "public"."correction" drop constraint "correction_topic_id_fkey";

create table "public"."tutor_prompt" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "text" text not null,
    "topic_id" bigint
);


alter table "public"."tutor_prompt" enable row level security;

alter table "public"."correction" drop column "topic_id";

alter table "public"."correction" add column "tutor_prompt_id" bigint not null;

alter table "public"."tutor_topic" drop column "prompt";

CREATE UNIQUE INDEX tutor_prompt_pkey ON public.tutor_prompt USING btree (id);

alter table "public"."tutor_prompt" add constraint "tutor_prompt_pkey" PRIMARY KEY using index "tutor_prompt_pkey";

alter table "public"."correction" add constraint "correction_tutor_prompt_id_fkey" FOREIGN KEY (tutor_prompt_id) REFERENCES tutor_prompt(id) ON DELETE CASCADE not valid;

alter table "public"."correction" validate constraint "correction_tutor_prompt_id_fkey";

alter table "public"."tutor_prompt" add constraint "tutor_prompt_topic_id_fkey" FOREIGN KEY (topic_id) REFERENCES tutor_topic(id) ON DELETE CASCADE not valid;

alter table "public"."tutor_prompt" validate constraint "tutor_prompt_topic_id_fkey";

grant delete on table "public"."tutor_prompt" to "anon";

grant insert on table "public"."tutor_prompt" to "anon";

grant references on table "public"."tutor_prompt" to "anon";

grant select on table "public"."tutor_prompt" to "anon";

grant trigger on table "public"."tutor_prompt" to "anon";

grant truncate on table "public"."tutor_prompt" to "anon";

grant update on table "public"."tutor_prompt" to "anon";

grant delete on table "public"."tutor_prompt" to "authenticated";

grant insert on table "public"."tutor_prompt" to "authenticated";

grant references on table "public"."tutor_prompt" to "authenticated";

grant select on table "public"."tutor_prompt" to "authenticated";

grant trigger on table "public"."tutor_prompt" to "authenticated";

grant truncate on table "public"."tutor_prompt" to "authenticated";

grant update on table "public"."tutor_prompt" to "authenticated";

grant delete on table "public"."tutor_prompt" to "service_role";

grant insert on table "public"."tutor_prompt" to "service_role";

grant references on table "public"."tutor_prompt" to "service_role";

grant select on table "public"."tutor_prompt" to "service_role";

grant trigger on table "public"."tutor_prompt" to "service_role";

grant truncate on table "public"."tutor_prompt" to "service_role";

grant update on table "public"."tutor_prompt" to "service_role";


